# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fights',
        ),
        migrations.RemoveField(
            model_name='fights',
            name='temp',
        ),
        migrations.AddField(
            model_name='fights',
            name='Event',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='mmaapp.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fights',
            name='Fighter1',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='mmaapp.Fighters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fights',
            name='Fighter2',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='mmaapp.Fighters'),
            preserve_default=False,
        ),
    ]
