# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmaapp', '0003_auto_20151218_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighters',
            old_name='weight',
            new_name='sherdog_profile',
        ),
        migrations.RemoveField(
            model_name='fighters',
            name='age',
        ),
        migrations.RemoveField(
            model_name='fighters',
            name='height',
        ),
        migrations.RemoveField(
            model_name='fighters',
            name='reach',
        ),
    ]
