# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmaapp', '0004_auto_20151218_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='fighters',
            options={'verbose_name_plural': 'Fighters'},
        ),
        migrations.AlterModelOptions(
            name='fights',
            options={'verbose_name_plural': 'Fights'},
        ),
        migrations.AlterModelOptions(
            name='promoter',
            options={'verbose_name_plural': 'Promoters'},
        ),
        migrations.AlterField(
            model_name='event',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmaapp.Promoter'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='Event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmaapp.Event'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='Fighter1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmaapp.Fighters'),
        ),
        migrations.AlterField(
            model_name='fights',
            name='Fighter2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='mmaapp.Fighters'),
        ),
    ]
