# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmaapp', '0005_auto_20151218_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighters',
            old_name='sherdog_profile',
            new_name='profile_link',
        ),
    ]
