# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mmaapp', '0006_auto_20151218_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 18, 15, 58, 36, 648840, tzinfo=utc)),
        ),
    ]
