# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mmaapp', '0007_event_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_day',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 18, 16, 20, 29, 631171, tzinfo=utc)),
        ),
    ]
