# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mmaapp', '0009_auto_20151218_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='promoter',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_day',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 18, 18, 42, 17, 201692, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Promoter',
        ),
    ]
